### ISSUE TITLE
mruby-cidr.gem git repo is not accessible

### ISSUE THREAD

**Issue by DarkKowalski** [mruby/mgem-list#316]
>name: mruby-cidr
description: CIDR class
author: kaihar4
website: https://github.com/kaihar4/mruby-cidr
protocol: git
repository: https://github.com/kaihar4/mruby-cidr.git
license: MIT

**Comment by matz** [comment]
Closed by 3208a2eedfb83134528be4565703b108f1e5e22c.
Since we cannot find any fork, this entry was removed.
