### ISSUE TITLE
mruby-pure-regexp.gem git repo is not accessible

### ISSUE THREAD

**Issue by DarkKowalski** [mruby/mgem-list#318]
>name: mruby-pure-regexp
description: Pure mruby Regexp
author: h2so5
website: https://github.com/h2so5/mruby-pure-regexp
protocol: git
repository: https://github.com/h2so5/mruby-pure-regexp.git
license: MIT

**Comment by matz** [comment]
Closed by 3208a2eedfb83134528be4565703b108f1e5e22c.
